/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.orderManagement;
import bean.User;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import util.authenticate.UserAuthentication;

public class OrderLogin extends javax.swing.JInternalFrame {

    public OrderLogin() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));        
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        validationLabel.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        validationLabel1 = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userNamejTextField = new javax.swing.JTextField();
        passwordjPasswordField = new javax.swing.JPasswordField();
        validationLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setEnabled(false);
        setFocusCycleRoot(false);
        setFocusable(false);
        setMinimumSize(new java.awt.Dimension(1007, 400));
        setPreferredSize(new java.awt.Dimension(1007, 400));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setAlignmentX(0.0F);
        contentPanel.setAlignmentY(0.0F);
        contentPanel.setAutoscrolls(true);
        contentPanel.setMinimumSize(new java.awt.Dimension(1007, 400));
        contentPanel.setPreferredSize(new java.awt.Dimension(1007, 400));
        contentPanel.setLayout(null);

        validationLabel1.setForeground(new java.awt.Color(255, 0, 0));
        contentPanel.add(validationLabel1);
        validationLabel1.setBounds(490, 240, 260, 0);

        clearButton.setBackground(new java.awt.Color(153, 153, 153));
        clearButton.setForeground(new java.awt.Color(51, 51, 51));
        clearButton.setText("CLEAR");
        clearButton.setBorder(null);
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        contentPanel.add(clearButton);
        clearButton.setBounds(660, 280, 90, 30);

        loginButton.setBackground(new java.awt.Color(105, 229, 73));
        loginButton.setForeground(new java.awt.Color(25, 117, 0));
        loginButton.setText("LOGIN");
        loginButton.setBorder(null);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        contentPanel.add(loginButton);
        loginButton.setBounds(550, 280, 100, 30);

        jPanel1.setBackground(new java.awt.Color(229, 229, 229));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/images/orderLoginCover.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel1.setBackground(new java.awt.Color(1, 1, 1));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1.setText("Order Manager Login");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        contentPanel.add(jPanel1);
        jPanel1.setBounds(0, 0, 260, 400);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Pawssword");
        contentPanel.add(jLabel2);
        jLabel2.setBounds(490, 180, 180, 16);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("User Name");
        contentPanel.add(jLabel4);
        jLabel4.setBounds(490, 130, 180, 16);

        userNamejTextField.setBackground(new java.awt.Color(255, 255, 255));
        userNamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNamejTextFieldActionPerformed(evt);
            }
        });
        contentPanel.add(userNamejTextField);
        userNamejTextField.setBounds(490, 150, 260, 24);

        passwordjPasswordField.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.add(passwordjPasswordField);
        passwordjPasswordField.setBounds(490, 200, 260, 22);

        validationLabel.setForeground(new java.awt.Color(204, 51, 0));
        validationLabel.setText("validation");
        contentPanel.add(validationLabel);
        validationLabel.setBounds(490, 230, 260, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNamejTextFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        validationLabel.setText("");
       
        if(String.valueOf(passwordjPasswordField.getPassword()).length() !=0 && userNamejTextField.getText().length() !=0){
            User user = new User(userNamejTextField.getText(), "",String.valueOf(passwordjPasswordField.getPassword()));
            String result = UserAuthentication.validateUser(user);
            if(result.equals("success")) {
                OrderHome orderHome = new OrderHome();
                contentPanel.removeAll();
                contentPanel.add(orderHome).setVisible(true);
            }else{
                validationLabel.setText(result);
            }
        }else{
           
            if(userNamejTextField.getText().length() == 0)
                validationLabel.setText("User ID Required!");
            if(String.valueOf(passwordjPasswordField.getPassword()).length() == 0)
                validationLabel.setText("User Password Required!");
            if(userNamejTextField.getText().length() == 0 && String.valueOf(passwordjPasswordField.getPassword()).length() == 0)
                validationLabel.setText("User ID or Password cannot be Empty!");
           
        }
       
    }//GEN-LAST:event_loginButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        userNamejTextField.setText("");
        passwordjPasswordField.setText("");
        validationLabel.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordjPasswordField;
    private javax.swing.JTextField userNamejTextField;
    private javax.swing.JLabel validationLabel;
    private javax.swing.JLabel validationLabel1;
    // End of variables declaration//GEN-END:variables
}
