/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.orderManagement;
import bean.Customer;
import bean.Item;
import bean.Order;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import service.OrderService;
import util.Utility.JUtility;
import util.Utility.PrintReport;
import view.orderManagement.CustomerPopUp.CustomerResponse;
import view.orderManagement.ItemPopUp.ItemResponse;


public class OrderHome extends javax.swing.JInternalFrame {
    private Order selectedOrder = new Order();
    public OrderHome() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));        
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        setDefaultsValues();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        itemValidationLabel = new javax.swing.JLabel();
        customerValidationLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        searchjTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        generateReportButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        browseItemButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        browseCustomerButton = new javax.swing.JButton();
        itemQuantityTextField = new javax.swing.JTextField();
        itemIDTextField = new javax.swing.JTextField();
        itemNameTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cusIDTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        custNameTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        orderIDLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        unitPriceTextField = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        customerValidationLbl = new javax.swing.JLabel();
        itemValidationLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setEnabled(false);
        setFocusCycleRoot(false);
        setFocusable(false);
        setMinimumSize(new java.awt.Dimension(1007, 400));
        setPreferredSize(new java.awt.Dimension(1007, 400));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setAlignmentX(0.0F);
        contentPanel.setAlignmentY(0.0F);
        contentPanel.setAutoscrolls(true);
        contentPanel.setMinimumSize(new java.awt.Dimension(1007, 400));
        contentPanel.setPreferredSize(new java.awt.Dimension(1007, 400));
        contentPanel.setLayout(null);

        itemValidationLabel.setForeground(new java.awt.Color(255, 0, 0));
        contentPanel.add(itemValidationLabel);
        itemValidationLabel.setBounds(10, 260, 320, 0);

        customerValidationLabel.setForeground(new java.awt.Color(255, 0, 0));
        contentPanel.add(customerValidationLabel);
        customerValidationLabel.setBounds(340, 260, 320, 0);

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Quantity :");
        contentPanel.add(jLabel6);
        jLabel6.setBounds(10, 340, 130, 20);

        searchjTextField.setText("Search");
        searchjTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearSearchField(evt);
            }
        });
        searchjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchjTextFieldActionPerformed(evt);
            }
        });
        searchjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTable(evt);
            }
        });
        contentPanel.add(searchjTextField);
        searchjTextField.setBounds(10, 30, 980, 24);

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Item ID", "Item Name", "Item Quantity", "Total Amount", "Order Date", "Customer ID", "Customer Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        orderTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setSelectedOrderToFields(evt);
            }
        });
        jScrollPane1.setViewportView(orderTable);

        contentPanel.add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 980, 160);

        generateReportButton.setBackground(new java.awt.Color(51, 51, 51));
        generateReportButton.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        generateReportButton.setForeground(new java.awt.Color(255, 255, 255));
        generateReportButton.setText("PRINT SELECTED ORDER");
        generateReportButton.setBorder(null);
        generateReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReportButtonActionPerformed(evt);
            }
        });
        contentPanel.add(generateReportButton);
        generateReportButton.setBounds(670, 360, 210, 30);

        addButton.setBackground(new java.awt.Color(255, 204, 0));
        addButton.setForeground(new java.awt.Color(51, 51, 51));
        addButton.setText("ADD");
        addButton.setBorder(null);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        contentPanel.add(addButton);
        addButton.setBounds(890, 240, 100, 30);

        updateButton.setBackground(new java.awt.Color(0, 102, 51));
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("UPDATE");
        updateButton.setBorder(null);
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        contentPanel.add(updateButton);
        updateButton.setBounds(890, 280, 100, 30);

        deleteButton.setBackground(new java.awt.Color(255, 51, 0));
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("DELETE");
        deleteButton.setBorder(null);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        contentPanel.add(deleteButton);
        deleteButton.setBounds(890, 320, 100, 30);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("ORDER MANAGEMENT");
        contentPanel.add(jLabel7);
        jLabel7.setBounds(10, 0, 190, 30);

        browseItemButton.setText("Browse Item");
        browseItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseItemButtonActionPerformed(evt);
            }
        });
        contentPanel.add(browseItemButton);
        browseItemButton.setBounds(160, 230, 170, 20);

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Select Item :");
        contentPanel.add(jLabel8);
        jLabel8.setBounds(10, 230, 130, 20);

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Item ID :");
        contentPanel.add(jLabel9);
        jLabel9.setBounds(10, 280, 130, 20);

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Item Name :");
        contentPanel.add(jLabel10);
        jLabel10.setBounds(10, 310, 130, 20);

        browseCustomerButton.setText("Browse Customer");
        browseCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseCustomerButtonActionPerformed(evt);
            }
        });
        contentPanel.add(browseCustomerButton);
        browseCustomerButton.setBounds(490, 230, 170, 20);

        itemQuantityTextField.setEditable(false);
        contentPanel.add(itemQuantityTextField);
        itemQuantityTextField.setBounds(160, 340, 170, 24);

        itemIDTextField.setEditable(false);
        contentPanel.add(itemIDTextField);
        itemIDTextField.setBounds(160, 280, 170, 24);

        itemNameTextField.setEditable(false);
        contentPanel.add(itemNameTextField);
        itemNameTextField.setBounds(160, 310, 170, 24);

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Customer ID :");
        contentPanel.add(jLabel12);
        jLabel12.setBounds(340, 280, 130, 20);

        cusIDTextField.setEditable(false);
        contentPanel.add(cusIDTextField);
        cusIDTextField.setBounds(490, 280, 170, 24);

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Customer Name :");
        contentPanel.add(jLabel13);
        jLabel13.setBounds(340, 310, 130, 20);

        custNameTextField.setEditable(false);
        contentPanel.add(custNameTextField);
        custNameTextField.setBounds(490, 310, 170, 24);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Order Date :");

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Total Amount :");

        totalLabel.setBackground(new java.awt.Color(51, 51, 51));
        totalLabel.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        totalLabel.setForeground(new java.awt.Color(51, 51, 51));
        totalLabel.setAlignmentX(SwingConstants.RIGHT);

        dateLabel.setForeground(new java.awt.Color(0, 0, 0));
        dateLabel.setText("2021-09-12");

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Order ID :");

        orderIDLabel.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orderIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderIDLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        contentPanel.add(jPanel1);
        jPanel1.setBounds(670, 230, 210, 120);

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Select Customer :");
        contentPanel.add(jLabel14);
        jLabel14.setBounds(340, 230, 130, 20);

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Unit Price :");
        contentPanel.add(jLabel16);
        jLabel16.setBounds(10, 370, 130, 20);

        unitPriceTextField.setEditable(false);
        contentPanel.add(unitPriceTextField);
        unitPriceTextField.setBounds(160, 370, 170, 24);

        clearButton.setBackground(new java.awt.Color(102, 102, 102));
        clearButton.setForeground(new java.awt.Color(255, 255, 255));
        clearButton.setText("CLEAR");
        clearButton.setBorder(null);
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        contentPanel.add(clearButton);
        clearButton.setBounds(890, 360, 100, 30);

        customerValidationLbl.setBackground(new java.awt.Color(255, 255, 255));
        customerValidationLbl.setForeground(new java.awt.Color(255, 0, 0));
        customerValidationLbl.setMaximumSize(new java.awt.Dimension(320, 16));
        customerValidationLbl.setMinimumSize(new java.awt.Dimension(320, 16));
        customerValidationLbl.setPreferredSize(new java.awt.Dimension(320, 16));
        contentPanel.add(customerValidationLbl);
        customerValidationLbl.setBounds(340, 260, 320, 16);

        itemValidationLbl.setBackground(new java.awt.Color(255, 255, 255));
        itemValidationLbl.setForeground(new java.awt.Color(255, 0, 0));
        itemValidationLbl.setMaximumSize(new java.awt.Dimension(320, 16));
        itemValidationLbl.setMinimumSize(new java.awt.Dimension(320, 16));
        itemValidationLbl.setPreferredSize(new java.awt.Dimension(320, 16));
        contentPanel.add(itemValidationLbl);
        itemValidationLbl.setBounds(10, 260, 320, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchjTextFieldActionPerformed

    private void generateReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReportButtonActionPerformed
        // TODO add your handling code here:
      
       if(selectedOrder.getoID() != null){
             PrintReport printReport = new PrintReport();
             printReport.generateSpecificOrderReport(selectedOrder);
             
       }else{
           JOptionPane.showMessageDialog(null, "Please Select Order Record to Print");
       }
    }//GEN-LAST:event_generateReportButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
//        clearLabels();
 itemValidationLabel.setText("Please Select an Item!");
        if(itemIDTextField.getText().isEmpty() || cusIDTextField.getText().isEmpty()){
            if(itemIDTextField.getText().isEmpty())
                itemValidationLbl.setText("Please Select an Item!");
            if(cusIDTextField.getText().isEmpty())
                customerValidationLbl.setText("Please Select a Customer!");
        }else{
            Order order = new Order();
            order.setoIID(itemIDTextField.getText());
            order.setoQuantity(Integer.parseInt(itemQuantityTextField.getText()));
            order.setoTotalPrice(Double.parseDouble(unitPriceTextField.getText()) * Integer.parseInt(itemQuantityTextField.getText()));
            order.setoCID(cusIDTextField.getText());
            order.setoDate(String.valueOf(LocalDate.now()));
            
            OrderService orderService = new OrderService();
            if(orderService.addOrder(order)){
                 JOptionPane.showMessageDialog(null, "Order Added Succesfully");
                setDefaultsValues();
            }else{
                JOptionPane.showMessageDialog(null, "Failed to Add Order");
            }
        }
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        clearLabels();
         if(selectedOrder.getoID() != null){
             if(itemIDTextField.getText().isEmpty() || cusIDTextField.getText().isEmpty()){
            if(itemIDTextField.getText().isEmpty())
                itemValidationLbl.setText("Please Select an Item!");
            if(cusIDTextField.getText().isEmpty())
                customerValidationLbl.setText("Please Select a Customer!");
        }else{
            Order order = new Order();
            order.setoID(selectedOrder.getoID());
            order.setoIID(itemIDTextField.getText());
            order.setoQuantity(Integer.parseInt(itemQuantityTextField.getText()));
            order.setoTotalPrice(Double.parseDouble(unitPriceTextField.getText()) * Integer.parseInt(itemQuantityTextField.getText()));
            order.setoCID(cusIDTextField.getText());
            order.setoDate(String.valueOf(LocalDate.now()));
            
            OrderService orderService = new OrderService();
            if(orderService.addOrder(order)){
                 JOptionPane.showMessageDialog(null, "Order Updated Succesfully");
                setDefaultsValues();
            }else{
                JOptionPane.showMessageDialog(null, "Failed to Update Order");
            }
        }
         }else{
              JOptionPane.showMessageDialog(null, "Please Select Order to Update");
         }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        clearLabels();
        if(selectedOrder.getoID() != null){
            int input = JOptionPane.showConfirmDialog(null, "Do you want to delete Selected Order?", "Confirm Your Action",
                    JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE);
            if (input == 0) {
                OrderService orderService = new OrderService();
                if (orderService.deleteOrder(selectedOrder.getoID())) {
                    JOptionPane.showMessageDialog(null, "Order Deleted Succesfully");
                    setDefaultsValues();
                } else {
                    JOptionPane.showMessageDialog(null, "Failed to Delete Order");
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please Select Order to Delete");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void clearSearchField(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearSearchField
        // TODO add your handling code here:
        searchjTextField.setText("");
    }//GEN-LAST:event_clearSearchField

    private void browseItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseItemButtonActionPerformed
        // TODO add your handling code here:
        ItemPopUp itemPopUp = new ItemPopUp(new ItemResponseImplementation());
        itemPopUp.setVisible(true);
    }//GEN-LAST:event_browseItemButtonActionPerformed

    private void browseCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseCustomerButtonActionPerformed
        // TODO add your handling code here:
        CustomerPopUp customerPopUp = new CustomerPopUp(new CustomerResponseImplementation());
        customerPopUp.setVisible(true);
    }//GEN-LAST:event_browseCustomerButtonActionPerformed

    private void setSelectedOrderToFields(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setSelectedOrderToFields
        // TODO add your handling code here:
         DefaultTableModel tableModel = (DefaultTableModel)orderTable.getModel();
        int modelRow = orderTable.getSelectedRow();
        int selectedRow = orderTable.convertRowIndexToModel(modelRow);
        selectedOrder.setoID(tableModel.getValueAt(selectedRow, 0).toString());
        selectedOrder.setoIID(tableModel.getValueAt(selectedRow, 1).toString());
        selectedOrder.setoIName(tableModel.getValueAt(selectedRow, 2).toString());
        selectedOrder.setoQuantity(Integer.valueOf(tableModel.getValueAt(selectedRow, 3).toString()));
        selectedOrder.setoTotalPrice(Double.valueOf(tableModel.getValueAt(selectedRow, 4).toString()));
        selectedOrder.setoDate(tableModel.getValueAt(selectedRow, 5).toString());
        selectedOrder.setoCID(tableModel.getValueAt(selectedRow, 6).toString());
        selectedOrder.setoCName(tableModel.getValueAt(selectedRow, 7).toString());
        
        
        orderIDLabel.setText(tableModel.getValueAt(selectedRow, 0).toString());
        itemIDTextField.setText(tableModel.getValueAt(selectedRow, 1).toString());
        itemNameTextField.setText(tableModel.getValueAt(selectedRow, 2).toString());
        itemQuantityTextField.setText(tableModel.getValueAt(selectedRow, 3).toString());
        totalLabel.setText("Rs : " +JUtility.numberDisplayWithCommasAndDecimalPlaces(Double.valueOf(tableModel.getValueAt(selectedRow, 4).toString())));
        dateLabel.setText(tableModel.getValueAt(selectedRow, 5).toString());
        cusIDTextField.setText(tableModel.getValueAt(selectedRow, 6).toString());
        custNameTextField.setText(tableModel.getValueAt(selectedRow, 7).toString());
        unitPriceTextField.setText(String.valueOf(Double.valueOf(tableModel.getValueAt(selectedRow, 4).toString()) / Integer.valueOf(tableModel.getValueAt(selectedRow, 3).toString())));
    }//GEN-LAST:event_setSelectedOrderToFields
    private void clearFields(){
        orderIDLabel.setText("");
        itemIDTextField.setText("");
        itemNameTextField.setText("");
        itemQuantityTextField.setText("");
        totalLabel.setText("");
        dateLabel.setText("");
        cusIDTextField.setText("");
        custNameTextField.setText("");
        unitPriceTextField.setText("");
        selectedOrder = new Order();
    }
    private void clearLabels(){
        customerValidationLbl.setText("");
        itemValidationLbl.setText("");
    }
    private void searchTable(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTable
        // TODO add your handling code here:
        searchFieldData(searchjTextField.getText());
    }//GEN-LAST:event_searchTable

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_clearButtonActionPerformed
    private class ItemResponseImplementation implements ItemResponse {

        @Override
        public void getRespose(Item responseItem) {
            //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            itemIDTextField.setText(responseItem.getiID());
            itemNameTextField.setText(responseItem.getiName());
            itemQuantityTextField.setText(String.valueOf(responseItem.getiQuantity()));
            unitPriceTextField.setText(String.valueOf(responseItem.getiSellingPrice()));
            totalLabel.setText("Rs : " +String.valueOf(JUtility.numberDisplayWithCommasAndDecimalPlaces(responseItem.getiQuantity() * responseItem.getiSellingPrice())));
        }
    }
    private class CustomerResponseImplementation implements CustomerResponse {

        @Override
        public void getRespose(Customer responseCustomer) {
            //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            cusIDTextField.setText(responseCustomer.getcID());
            custNameTextField.setText(responseCustomer.getcName());
        }
    }
    private void loadTableData() {
        DefaultTableModel tableModel = (DefaultTableModel) orderTable.getModel();
        tableModel.setNumRows(0);
        OrderService orderService = new OrderService();
        for (Order order : orderService.loadOrderList()) {
            String orderList[] = {order.getoID(), order.getoIID(), order.getoIName(), String.valueOf(order.getoQuantity()),String.valueOf(order.getoTotalPrice()), order.getoDate(), order.getoCID(), order.getoCName()};
            tableModel.addRow(orderList);
        }
    }
    private void searchFieldData(String filter) {
        if (filter.length() !=0 ) {
            DefaultTableModel tableModel = (DefaultTableModel) orderTable.getModel();
            TableRowSorter<DefaultTableModel> tableRow = new TableRowSorter<DefaultTableModel>(tableModel);
            orderTable.setRowSorter(tableRow);
            tableRow.setRowFilter(RowFilter.regexFilter(String.valueOf(filter)));
        } else {
            DefaultTableModel tableModel = (DefaultTableModel) orderTable.getModel();
            TableRowSorter<DefaultTableModel> tableRow = new TableRowSorter<DefaultTableModel>(tableModel);
            orderTable.setRowSorter(tableRow);
            tableRow.setRowFilter(RowFilter.regexFilter("(?i)"+filter));
        }

    }
    
    private void setDefaultsValues() {
        loadTableData();
        clearFields();
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton browseCustomerButton;
    private javax.swing.JButton browseItemButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JTextField cusIDTextField;
    private javax.swing.JTextField custNameTextField;
    private javax.swing.JLabel customerValidationLabel;
    private javax.swing.JLabel customerValidationLbl;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton generateReportButton;
    private javax.swing.JTextField itemIDTextField;
    private javax.swing.JTextField itemNameTextField;
    private javax.swing.JTextField itemQuantityTextField;
    private javax.swing.JLabel itemValidationLabel;
    private javax.swing.JLabel itemValidationLbl;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel orderIDLabel;
    private javax.swing.JTable orderTable;
    private javax.swing.JTextField searchjTextField;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JTextField unitPriceTextField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
